# pandas - "A melhor biblioteca do Python para Dados"

- Quase sempre que você for trabalhar com dados no Python você vai usar o pandas, então é importante você saber trabalhar com essa biblioteca muito bem

- Vamos aprender os principais comandos e os princípios básicos do pandas

- Faça o download do Gabarito desse arquivo e use como uma cartilha de consulta (Link na descrição)

### Importando o pandas

In [1]:
import pandas as pd
pd.options.display.float_format = '{:.2f}'.format

### Criando um dataframe a partir de um dicionário

In [2]:
# dataframe = pd.DataFrame()
venda = {'data': ['15/02/2021', '16/02/2021'],
         'valor': [500, 300],
         'produto': ['feijao', 'arroz'],
         'qtde': [50, 70],
        }
vendas_df = pd.DataFrame(venda)

### Visualização dos Dados
    - print
    - display

In [3]:
display(vendas_df)

         data  valor produto  qtde
0  15/02/2021    500  feijao    50
1  16/02/2021    300   arroz    70

### Importando arquivos e bases de dados

In [4]:
vendas_df = pd.read_excel("Vendas.xlsx")
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

### Resumos de Visualização de Dados simples e úteis
    - head
    - shape
    - describe

In [5]:
display(vendas_df.head(10))
print(vendas_df.shape)
display(vendas_df.describe())

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248
6,5,2019-01-02,Shopping Barra,Calça,1,170,170
7,6,2019-01-02,Shopping Ibirapuera,Polo Listrado,4,149,596
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105

(93910, 7)

,Código Venda,Data,Quantidade,Valor Unitário,Valor Final
count,93910.00,93910,93910.00,93910.00,93910.00
mean,32464.76,2019-06-16 23:52:28.265360896,2.17,191.73,414.86
min,1.00,2019-01-01 00:00:00,1.00,30.00,30.00
25%,16204.00,2019-03-26 00:00:00,1.00,100.00,156.00
50%,32367.00,2019-06-17 00:00:00,2.00,155.00,274.00
75%,48793.75,2019-09-08 00:00:00,3.00,248.00,524.00
max,65014.00,2019-11-30 00:00:00,5.00,750.00,3750.00
std,18809.01,NaN,1.26,145.22,434.85

### Pegar 1 coluna (e os pd.Series)

In [13]:
produtos = vendas_df [['Produto', 'Quantidade']]
display(produtos)

                 Produto  Quantidade
0         Sapato Estampa           1
1               Camiseta           2
2          Sapato Xadrez           1
3                Relógio           3
4           Chinelo Liso           1
...                  ...         ...
93905     Mochila Xadrez           2
93906  Pulseira Listrado           2
93907     Cueca Listrado           3
93908     Pulseira Linho           5
93909      Casaco Xadrez           4

[93910 rows x 2 columns]

### .loc, um método muito importante
    - Pegar 1 linha
    - Pegar linhas de acordo com alguma condição
    - Pegar linhas e colunas específicas
    - Pegar 1 valor específico

In [26]:
#pegar uma linha
#display(vendas_df.loc[1:5])

#pegar linhas que correspondem a uma condição

#vendas_norte_df = vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping']

#display(vendas_norte_df)

# pegar varias linhas e colunas usando loc
vendas_norte_df = vendas_df.loc[vendas_df ['ID Loja'] == 'Norte Shopping', ["ID Loja", "Produto", "Quantidade", "Valor Final"]]
display(vendas_norte_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105
100,73,2019-01-02,Norte Shopping,Cueca Xadrez,5,60,300
...,...,...,...,...,...,...,...
93716,64888,2019-11-30,Norte Shopping,Polo Xadrez,1,142,142
93754,64914,2019-11-30,Norte Shopping,Calça Liso,1,190,190
93755,64914,2019-11-30,Norte Shopping,Casaco Estampa,2,256,512
93756,64914,2019-11-30,Norte Shopping,Gorro,2,80,160
93852,64980,2019-11-30,Norte Shopping,Bermuda Linho,1,195,195

### Adicionar 1 coluna

### Adicionar 1 linha
    - Linhas de um complemento da base de dados

### Excluir linhas e colunas

### Valores Vazios
    - Deletar linhas/colunas vazias
    - Deletar linhas que possuem valores vazios
    - Preencher valores vazios (média e último valor)

### Calcular Indicadores
    - Groupby
    - Value Counts

### Mesclar 2 dataframes (Procurar informações de um dataframe em outro)

### Como continuar aprendendo?

### Minicurso Gratuito de Análise de Dados com Python na Descrição